version: '3'
services:
  postgres:
    image: mdillon/postgis:10
    ports:
      - 5433:5432
    environment:
      PGPASSWORD: postgres
    volumes:
      - .docker/data/postgresql:/var/lib/postgresql/data
  redis:
    image: redis:4.0.10
    ports:
      - 6380:6379
    volumes:
      - .docker/data/redis:/data
